config/routes.rb
Rails.application.routes.draw do

  get 'login' , to: 'sessions#new'
  post 'login' , to: 'sessions#create'
  delete 'login' , to: 'sessions#destroy'




  resources :tasks
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  #validates :title, presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
  before_validation { email.downcase! }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :login_required

  before_action :set_search
  protect_from_forgery with: :exception
  include SessionsHelper

  def set_search
  #@search = Article.search(params[:q])
  @search = Task.ransack(params[:q]) #ransackメソッド推奨
  @search_tasks = @search.result.page(params[:page])
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end


  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  PER = 8

  #def index
    #@tasks = Task.all
    #@tasks = current_user.tasks

    #@tasks = Task.page(params[:page]).per(PER)
  #end
  #def index
  #@tasks = current_user.tasks
  #end

  def index
  @q = current_user.tasks.ransack(params[:q])
  @tasks = @q.result(distinct: true).page(params[:page])

  respond_to do |format|
    format.html
    format.csv { send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" } # --- ②
  end
 end

  def show
  @task = Task.find_by(id: params[:id])
  # 変数@userを定義してください
  #@user = User.find_by(id: @task.user_id)
  end


def new
  @task = Task.new
end

def create
   @task = current_user.tasks.build(task_params)
   #binding.pry
   if @task.save
   #binding.pry
     redirect_to task_path(@task), notice: ('common.flash.created')
   else
     flash.now[:alert] = @task.errors.full_messages.join('。')
     @task.errors.delete(:content)
     render :new
   end
 end

 #def creates
   #@task = current_user.tasks.build(task_params)
   #if @task.save
     #redirect_to task_path(@task), notice: ('common.flash.created')
   #else
     #flash.now[:alert] = @task.errors.full_messages.join('。')
     #@task.errors.delete(:content)
     #render :new
   #end


 def confirm
    #@task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)
    #binding.pry
    render :new if @task.invalid?
  end

def edit
  @task = Task.find(params[:id])
end

#def update
  #@task = Task.find(params[:id])
  #if @task.update(task_params)
    #flash[:success] = 'タスクが編集されました'
    #redirect_to @task
  #else
    #flash.now[:danger] = 'タスクが編集されませんでした'
    #render :new
  #end
#end

def update
  if @task.update(task_params)
    redirect_to task_path(@task), notice: t('common.flash.updated')
  else
    flash.now[:alert] = @task.errors.full_messages.join('。')
    @task.errors.delete(:content)
    render :edit
  end
end


def destroy
  @task = Task.find(params[:id])
  @task.destroy

  flash[:success] = 'タスクが削除されました'
  redirect_to @task
end

def confirm_new
   @task = current_user.tasks.new(task_params)
   render :new unless @task.valid?
end

private

def task_params
  params.require(:task).permit(:content)
end


def set_task
  @task = current_user.tasks.find(params[:id])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end


  def new
    @user = User.new
  end


  def create
  @user = User.new(user_params)
  if @user.save
    redirect_to users_path(@user), notice: "ユーザー「#{@user.name}」を登録しました。"

  else
    render 'new'
  end
end


  def show
   @user = User.find(params[:id])
   @task = Task.find_by(id: params[:id])
 end

 def destroy
  @user = User.find(params[:id])
  @user.destroy
  redirect_to users_path(@user), notice: "ユーザー「#{@user.name}」を削除しました。"
end


  private

  def user_params
    #params.require(:user).permit(:name, :email, :password,:password_confirmation)
    params.require(:user).permit(:name, :email, :password,:password_confirmation, :user_id)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>
  <div><%= task %></div>
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TaskApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  dl.searchbox
    = search_form_for @search, url: tasks_path do |f|
      dt
        = f.text_field :content_cont ,placeholder: '検索するテキストを入力...'
      dd
        = f.submit ("検索") , class: 'search-btn'
  body
    - flash.each do |key, value|
      = content_tag(:div, value, class: "#{key}")
    = yield

app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li= message

= form_with model: task, local: true do |f|
  .form-group
    = f.label :content
    = f.text_field :content, class: 'form-control', id: 'task_content'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h1 タスクの更新

.nav.justify-content-end
 = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form' , locals: {task: @task}

app/views/tasks/index.html.slim
h1 タスク一覧


= link_to '新規登録', new_task_path, class: 'btn btn-primary mb-3'

table.table.table-hover
  thread.thread-default
    tr
      th= Task.human_attribute_name(:name)
      th= Task.human_attribute_name(:crated_at)
      th
    tbody
      - @tasks.each do |task|
        tr
          td= link_to task.content, task
          td= task.created_at
          td
            = link_to '編集' , edit_task_path(task), class: 'btn btn-primary mr-3'
            = link_to '削除' , task, method: :delete, data: { confirm: "タスク 「#{task.content}を削除します。宜しいでしょうか？"}, class: 'btn btn-danger'

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
 = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form' , locals: {task: @task}

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify_content-end
   = link_to '一覧' , tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr
      th= Task.human_attribute_name(:name)
      td= @task.content
    tr
      th= Task.human_attribute_name(:content)
      td= simple_format(h(@task.content), {}, sanitize: false, wrapper_tag: "div")

    tr
      th= Task.human_attribute_name(:craeted_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:id)
      td= @task.updated_at

= link_to '編集' , edit_task_path, class: 'btn btn primary mr-3'

app/views/users/_form.html.slim
= form_with model:user, local: true do |f|
  .form-group
    =f.label :name, '名前'
    =f.text_field :name, class: 'form-control'

  .form-group
    =f.label :email, 'メールアドレス'
    =f.text_field :email, class: 'form-control'

  .form-group
    =f.label :password, 'パスワード'
    =f.password_field :password, class: 'form-control'

  .form-group
    =f.label :password_confirmation, 'パスワード(確認)'
    =f.password_field :password_confirmation, class: 'form-control'

  = f.submit nil, class: 'btn btn-primary'

app/views/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
 = link_to '一覧', users_path, class: 'nav-link'

 = render partial: 'form', locals: {user: @user}

app/views/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thread.thread-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th


    tbody
      - @users.each do |user|
        tr
          td= user.name
          td= user.email
          td= user.created_at
          td= user.updated_at


          td
            = link_to '編集' , edit_user_path(user), class: 'btn btn-primary mr-3'
            

app/views/users/new.html.slim
h1
  | Sign up
- if @user.errors.any?
  #error_explanation
    h2
      = pluralize(@user.errors.count, "error")
      |  prohibited this @user from being saved:
    ul
      - @user.errors.full_messages.each do |message|
        li
          = message
= form_with(model: @user, local: true) do |f|
  = f.label :name
  = f.text_field :name
  = f.label :email
  = f.email_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = f.submit "Create my account"
.dropdown
  button#dropdownMenu1.btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"]
    |  ドロップダウン
    span.caret
  ul.dropdown-menu[aria-labelledby="dropdownMenu1"]
    li
      a[href="#"]
        | Task1
    li
      a[href="#"]
        | Task2
    li
      a[href="#"]
        | Task3
    li
      a[href="#"]
        | Task4

app/views/users/show.html.slim
h1 ユーザーの詳細

.nav.justify_content-end
   = link_to '一覧' , users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email

    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to 'タスク', new_task_path

= link_to '編集' , edit_user_path, class: 'btn btn primary mr-3'
= link_to '削除' , [@user], method: :delete,
  data: { confirm: "ユーザー 「#{@user.name}を削除します。宜しいでしょうか？"}, class: 'btn btn-danger'